- name: Download tabby release yaml
  get_url:
    url: https://github.com/Eugeny/tabby/releases/latest/download/latest-x64.yml
    dest: /tmp/latest-x64.yml
- name: Save checksums as variable
  shell: cat /tmp/latest-x64.yml
  register: tabby_release_yaml
- name: Install tabby terminal emulator
  become: true
  apt:
    deb: "https://github.com/Eugeny/tabby/releases/latest/download//tabby-{{ (tabby_release_yaml.stdout | from_yaml).version }}-linux-x64.deb"
- name: Fix any broken dependencies
  become: true
  apt:
    state: fixed
