- name: Provision Kali
  become: true
  block:
    - name: Install base packages
      apt:
        pkg: kali-linux-large
    # opting to use the vanilla code package from microsoft
    - name: Remove conflicting vscode package
      apt:
        pkg: code-oss
        state: absent
    - name: Install other deb packages
      tags: other-debs
      apt:
        deb: "{{ item }}"
      loop:
        - "https://update.u.is/downloads/linux/utopia-latest.amd64.deb"
# Also install i2p (https://geti2p.net/en/), tor, zeronet
