---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: utility-belt-secret
  namespace: utility-belt
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: utility-belt-secret
  dataFrom:
    - extract:
        key: /utility-belt/utility-belt-secret
---
