- name: Detect omf installation
  stat:
    path: "{{ user_home }}/.local/share/omf/pkg/omf/functions/omf.fish"
  register: omf_function
- name: Install oh-my-fish
  when: ansible_facts.os_family != 'Darwin' and omf_function.stat.exists == False
  block:
    - name: Install zoxide deb package
      become: true
      apt:
        deb: "https://github.com/ajeetdsouza/zoxide/releases/download/v{{ zoxide_version }}/zoxide_{{ zoxide_version }}_amd64.deb"
      when: ansible_facts.os_family == "Debian"
    - name: Clone fzf repo
      git:
        repo: https://github.com/junegunn/fzf.git
        dest: "{{ user_home }}/.fzf"
        depth: 1
        version: "{{ fzf_version }}"
    - name: Install fzf
      command: "{{ user_home }}/.fzf/install --all"
    - name: Download oh-my-fish checksum
      uri:
        url: https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install.sha256
        return_content: true
      register: omf_checksum_result
    - name: Download oh-my-fish
      get_url:
        url: https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install
        dest: /tmp/install
        checksum: "sha256:{{ omf_checksum_result.content | split | first }}"
    - name: Install oh-my-fish
      command: fish /tmp/install --noninteractive --yes
    - name: Delete oh-my-fish installer
      file:
        path: /tmp/install
        state: absent
    - name: Install fish plugins
      command: fish -c "omf install bass"
