- name: Provision Ubuntu
  become: true
  block:
    - name: Install base packages
      apt:
        pkg:
          # - avahi-utils
          - bat
          - bpftrace
          - exa
          - htop
          - ripgrep
