---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: mysql-image-repository
  namespace: azerothcore
spec:
  image: docker.io/bitnami/mysql
  interval: 30m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: mysql-image-policy
  namespace: azerothcore
spec:
  imageRepositoryRef:
    name: mysql-image-repository
  filterTags:
    pattern: '^(?P<version>8\.[0-9]{1,2}\.[0-9]{1,2})-debian-11-r(?P<bnrev>[0-9]+)$'
    extract: '$version$bnrev'
  policy:
    semver:
      range: '>= 8.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: mysql-image-update-automation
  namespace: azerothcore
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: flux@noreply.kja.us
        name: Flux
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: master
  update:
    path: ./kubernetes/apps/azerothcore/mysql
    strategy: Setters
---
