apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: azerothcore
spec:
  interval: 30m
  chart:
    spec:
      chart: mysql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 30m
  values:
    image:
      # this is probably not a good idea since MySQL could restart in the middle of a session
      # tag: 8.0.34-debian-11-r30 # {"$imagepolicy": "azerothcore:mysql-image-policy:tag"}
      tag: 8.0.34-debian-11-r30
    auth:
      createDatabase: false
      existingSecret: mysql-secret
    metrics:
      enabled: false
    primary:
      containerSecurityContext:
        runAsUser: 1000
      persistence:
        existingClaim: mysql-volume-claim
      podSecurityContext:
        fsGroup: 1000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-claim
  namespace: azerothcore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-storage
  volumeName: azerothcore-mysql-volume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: azerothcore-mysql-volume
spec:
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: mysql-volume-claim
    namespace: azerothcore
  hostPath:
    path: /data/azerothcore/mysql
    type: Directory
  capacity:
    storage: 20Gi
  # persistentVolumeReclaimPolicy: Retain # <- default
  storageClassName: local-storage
  volumeMode: Filesystem
