---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # create namespace first
  - namespace.yaml
  - kube-prometheus-externalsecret.yaml
  - kube-prometheus-flux.yaml
  - kube-prometheus.yaml
---
