- name: Download Rust installer
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup-init.sh
    mode: 0755
- name: Run Rust installer
  command: /tmp/rustup-init.sh -y
- name: Set default Rust version
  command: rustup default stable
  environment:
    PATH: "{{ user_home }}/.cargo/bin:{{ ansible_env.PATH }}"
- name: Remove Rust installer
  file:
    path: /tmp/rustup-init.sh
    state: absent
