---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-basic-auth
  namespace: kube-system
type: Opaque
stringData:
# htpasswd -nb username password | openssl base64
  users: |2
    super_secret_base64_password
