---
apiVersion: v1
kind: Secret
metadata:
  name: wireguard-config-secret
  namespace: txwg
type: Opaque
stringData:
  wireguard_config_data: |
    [Interface]
    PrivateKey = super_secret_wireguard_private_key
    Address = wireguard_address
    # DNS = 8.8.8.8
    DNS = wireguard_dns
    # ListenPort = 51820
    PostUp = DROUTE=$(ip route | grep default | awk '{print $3}'); ip route add 10.42.0.0/19 via $DROUTE; ip route add 10.0.0.0/24 via $DROUTE; ip route add 192.168.1.0/24 via $DROUTE; iptables -A OUTPUT -d 10.42.0.0/19 -j ACCEPT; iptables -I OUTPUT -d 10.0.0.0/24 -j ACCEPT; iptables -I OUTPUT -d 192.168.1.0/24 -j ACCEPT; iptables -A OUTPUT ! -o %i -m mark ! --mark $(wg show %i fwmark) -m addrtype ! --dst-type LOCAL -j REJECT
    PreDown = DROUTE=$(ip route | grep default | awk '{print $3}'); ip route del 192.168.1.0/24 via $DROUTE; ip route del 10.0.0.0/24 via $DROUTE; ip route del 10.42.0.0/19 via $DROUTE; iptables -D OUTPUT ! -o %i -m mark ! --mark $(wg show %i fwmark) -m addrtype ! --dst-type LOCAL -j REJECT; iptables -D OUTPUT -d 192.168.1.0/24 -j ACCEPT; iptables -D OUTPUT -d 10.0.0.0/24 -j ACCEPT; iptables -D OUTPUT -d 10.42.0.0/19 -j ACCEPT

    [Peer]
    PublicKey = wireguard_public_key
    Endpoint = wireguardendpoint:wireguardport
    AllowedIPs = 0.0.0.0/0
---
apiVersion: v1
kind: Secret
metadata:
  name: transmission-secret
  namespace: txwg
type: Opaque
stringData:
  password: super_secret_base64_password
