---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # unused while we're sourcing certs from Letsencrypt
  # - flight-cluster-issuer.yaml
  - letsencrypt-cluster-issuer-prod.yaml
  - letsencrypt-cluster-issuer-staging.yaml
---
