---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: example@example.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      # - selector:
      #     dnsNames:
      #       # - "*.flight.kja.us"
      #       - '*.kja.us'
      - dns01:
          webhook:
            config:
              apiKeySecretRef:
                name: godaddy-api-key
                key: token
              production: true
              ttl: 600
            groupName: flight.kja.us
            solverName: godaddy
      # - http01:
      #     ingress:
      #       class: nginx
---
