---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flux-notification-secret
  namespace: flux-system
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: flux-notification-secret
  dataFrom:
    - extract:
        key: /flux-system/flux-notification-secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flux-webhook-secret
  namespace: flux-system
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: flux-webhook-secret
  dataFrom:
    - extract:
        key: /flux-system/flux-webhook-secret
---
