---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 30m
  chart:
    spec:
      chart: gitlab
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      interval: 30m
  valuesFrom:
    - kind: ConfigMap
      name: gitlab-chart-values
---
