---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backup-s3-credentials
  namespace: gitlab
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: backup-s3-credentials
  dataFrom:
    - extract:
        key: /gitlab/backup-s3-credentials
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: initial-root-password
  namespace: gitlab
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    # The naming of this secret is specific:
    # https://docs.gitlab.com/charts/installation/secrets.html#initial-root-password
    name: gitlab-gitlab-initial-root-password
  dataFrom:
    - extract:
        key: /gitlab/initial-root-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-secret
  namespace: gitlab
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    # The naming of this secret is specific:
    # https://docs.gitlab.com/charts/installation/secrets.html#redis-password
    name: gitlab-redis-secret
  dataFrom:
    - extract:
        key: /gitlab/redis-secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-password
  namespace: gitlab
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    # The naming of this secret is specific:
    # https://docs.gitlab.com/charts/installation/secrets.html#postgresql-password
    name: gitlab-postgresql-password
  dataFrom:
    - extract:
        key: /gitlab/postgresql-password
---
