---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # create namespace first
  - namespace.yaml
  - gitlab-externalsecret.yaml
  - gitlab-volumes.yaml
  - gitlab.yaml
configMapGenerator:
  - name: gitlab-chart-values
    namespace: gitlab
    files:
      - values.yaml=values.yaml
  - name: backup-extra-env-vars
    namespace: gitlab
    literals:
      - SKIP_REPOSITORIES_PATHS=kja/azerothcore-wotlk
configurations:
  - kustomizeconfig.yaml
---
