- name: Provision dnsmasq
  tags:
    - dnsmasq
    - dns
  block:
    - name: Install dnsmasq package
      apt:
        pkg: dnsmasq
    - name: Install dnspython package
      become: false
      pip:
        name: dnspython>2.2.0,<2.3.0
      delegate_to: localhost
    - debug:
        var: ansible_host
    - name: Copy dnsmasq config
      template:
        src: 00-dhcp-vmbr0.conf.j2
        dest: /etc/dnsmasq.d/00-dhcp-vmbr0.conf
        mode: 0644
  notify: Restart dnsmasq
