- name: Gather the package facts
  package_facts:
    manager: auto
  tags: friendly-shell
  when: ansible_facts.os_family != 'Darwin'
- name: Install fish shell (Debian)
  become: true
  tags: friendly-shell
  block:
    - name: Create /etc/apt/keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
    - name: Add OpenSUSE PGP public key
      shell: wget -qO - https://download.opensuse.org/repositories/shells:fish:release:3/Debian_11/Release.key | gpg --dearmor | tee /etc/apt/keyrings/shells_fish_release_3.gpg
    - name: Add OpenSUSE apt repository
      apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/shells_fish_release_3.gpg] https://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_11/ /
        state: present
        filename: shells:fish:release:3
    - name: Install fish shell (Debian)
      apt:
        update_cache: true
        pkg: fish
    - name: Make fish the default shell (Debian)
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        shell: /usr/bin/fish
- name: Install fish shell (FreeBSD)
  become: true
  tags: friendly-shell
  block:
    - name: Install fish shell (FreeBSD)
      environment:
        BATCH: 'yes'
      shell: |
        cd /usr/ports/shells/fish
        pkg info -e fish
        [ $? = 1 ] && make reinstall && make clean
        exit 0
    - name: Make fish the default shell (FreeBSD)
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        shell: /usr/local/bin/fish
  when: ansible_facts.os_family == 'FreeBSD'
- name: Install fish shell (macOS)
  tags: friendly-shell
  block:
    - name: Install fish shell (macOS)
      community.general.homebrew:
        name: fish
        update_homebrew: true
  when: ansible_facts.os_family == 'Darwin'
