---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # create namespace first
  - namespace.yaml
  - wireguard-externalsecret.yaml
  - wireguard-flux.yaml
  - wireguard.yaml
---
