---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wireguard-ui-secret
  namespace: wireguard
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: wireguard-ui-secret
  dataFrom:
    - extract:
        key: /wireguard/wireguard-ui-secret
---
