- name: Install Starship (Debian)
  become: true
  tags: friendly-shell
  block:
    - name: Download starship
      get_url:
        url: https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz
        dest: /tmp/starship-x86_64-unknown-linux-gnu.tar.gz
        checksum: sha256:https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz.sha256
    - name: Decompress starship binary into /usr/local/bin
      unarchive:
        src: /tmp/starship-x86_64-unknown-linux-gnu.tar.gz
        dest: /usr/local/bin
        remote_src: true
    - name: Clean up downloaded artifacts
      file:
        path: /tmp/starship-x86_64-unknown-linux-gnu.tar.gz
        state: absent
  when: ansible_facts.os_family == "Debian"
- name: Install Starship (FreeBSD)
  community.general.cargo:
    name: starship
    state: latest
  environment:
    PATH: "{{ user_home }}/.cargo/bin:{{ ansible_env.PATH }}"
  tags: friendly-shell
  when: ansible_facts.os_family == "FreeBSD"
- name: Permit starship-specific environment variables over SSH
  become: true
  copy:
    content: |
      AcceptEnv STARSHIP_CUSTOM_*
      # PrintLastLog no
    dest: /etc/ssh/sshd_config.d/99-acceptenv-starship-custom.conf
  notify: Reload sshd
  tags: friendly-shell
  when: ansible_facts.os_family != 'Darwin'
