---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: gitea-postgresql
  namespace: gitea
resources:
  # create namespace first
  - namespace.yaml
  - postgresql-externalsecret.yaml
  - postgresql.yaml
---
