---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - public-ip-cronjob.yaml
  - public-ip-externalsecret.yaml
configMapGenerator:
  - name: public-ip-scripts
    namespace: external-dns
    files:
      - fetch_public_ip.sh=fetch_public_ip.sh
---
