---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: public-ip-secret
  namespace: external-dns
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: public-ip-secret
  dataFrom:
    - extract:
        key: /external-dns/public-ip-secret
---
