---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: adguardhome
  namespace: flux-system
spec:
  dependsOn:
    - name: outland-wildcard-cert
  interval: 30m
  path: "./kubernetes/apps/adguardhome"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: ariang
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: external-secrets-stores
#   interval: 30m
#   path: "./kubernetes/apps/ariang"
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
# ---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: azerothcore
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-stores
    - name: azerothcore-mysql
  interval: 30m
  path: "./kubernetes/apps/azerothcore"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: azerothcore-mysql
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-stores
    - name: kube-prometheus
  interval: 30m
  path: "./kubernetes/apps/azerothcore/mysql"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: gitea
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: external-secrets-stores
#     - name: gitea-postgresql
#   interval: 30m
#   path: "./kubernetes/apps/gitea"
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: gitea-postgresql
#   namespace: flux-system
# spec:
#   interval: 30m
#   path: "./kubernetes/apps/gitea/postgresql"
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
# ---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitlab
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-stores
  interval: 30m
  path: "./kubernetes/apps/gitlab"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mediapipe
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-stores
    - name: kube-prometheus
  interval: 30m
  path: "./kubernetes/apps/mediapipe"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: uptime-kuma
  namespace: flux-system
spec:
  interval: 30m
  path: "./kubernetes/apps/uptime-kuma"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: utility-belt
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-stores
  interval: 30m
  path: "./kubernetes/apps/utility-belt"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wireguard
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-stores
  interval: 30m
  path: "./kubernetes/apps/wireguard"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---

