---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus
  interval: 30m
  path: "./kubernetes/infrastructure/controllers/cert-manager"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  dependsOn: []
  interval: 30m
  path: "./kubernetes/infrastructure/controllers/cilium"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-issuers
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 30m
  path: "./kubernetes/infrastructure/configs/cluster-issuers"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: device-plugin-operator
#   namespace: flux-system
# spec:
#   interval: 30m
#   path: "./kubernetes/infrastructure/controllers/device-plugin-operator"
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   healthChecks:
#     - apiVersion: apps/v1
#       kind: Deployment
#       name: inteldeviceplugins-controller-manager
#       namespace: device-plugins
# ---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-stores
  interval: 30m
  path: "./kubernetes/infrastructure/controllers/external-dns"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 30m
  path: "./kubernetes/infrastructure/controllers/external-secrets"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-stores
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets
    - name: vault
  interval: 30m
  path: "./kubernetes/infrastructure/configs/external-secrets-stores"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: gpu-device-plugin
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: device-plugin-operator
#   interval: 30m
#   path: "./kubernetes/infrastructure/controllers/gpu-device-plugin"
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
# ---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: godaddy-webhook
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
    - name: external-secrets-stores
  interval: 30m
  path: "./kubernetes/infrastructure/controllers/godaddy-webhook"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus
    - name: outland-wildcard-cert
  interval: 30m
  path: "./kubernetes/infrastructure/controllers/ingress-nginx"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-additions
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-stores
  interval: 30m
  path: "./kubernetes/infrastructure/configs/flux-additions"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-repositories
  namespace: flux-system
spec:
  interval: 30m
  path: "./kubernetes/infrastructure/configs/helm-repositories"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: kubernetes-replicator
#   namespace: flux-system
# spec:
#   interval: 30m
#   path: "./kubernetes/infrastructure/controllers/kubernetes-replicator"
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
# ---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-stores
  interval: 30m
  path: "./kubernetes/infrastructure/controllers/kube-prometheus"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 30m
  path: "./kubernetes/infrastructure/controllers/kyverno"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno-policies
  namespace: flux-system
spec:
  dependsOn:
    - name: kyverno
  interval: 30m
  path: "./kubernetes/infrastructure/configs/kyverno-policies"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-storage-class
  namespace: flux-system
spec:
  interval: 30m
  path: "./kubernetes/infrastructure/configs/local-storage-class"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: outland-wildcard-cert
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 30m
  path: "./kubernetes/infrastructure/configs/outland-wildcard-cert"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: reloader
  namespace: flux-system
spec:
  dependsOn: []
  interval: 30m
  path: "./kubernetes/infrastructure/controllers/reloader"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: routeros-controller
  namespace: flux-system
spec:
  dependsOn: []
  interval: 30m
  path: "./kubernetes/infrastructure/controllers/routeros-controller"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault
  namespace: flux-system
spec:
  dependsOn: []
    # chart option (?) turned off because circular dependency
    # kube-prometheus -> external-secrets -> vault
    # - name: kube-prometheus
  interval: 30m
  path: "./kubernetes/infrastructure/controllers/vault"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: volsync
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: external-secrets-stores
#     - name: kube-prometheus
#   interval: 30m
#   path: "./kubernetes/infrastructure/controllers/volsync"
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
# ---
