---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: prometheus
spec:
  ports:
    - port: 80
      targetPort: 9090
  selector:
    app: prometheus
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
  namespace: prometheus
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prometheus.flight.kja.us`)
      kind: Rule
      services:
        - name: prometheus
          namespace: prometheus
          port: 9090
          kind: Service
          scheme: http
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-claim
  namespace: prometheus
  labels:
    app: prometheus
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: prometheus
data:
  # prometheus.rules: |-
  #   groups:
  #   - name: devopscube demo alert
  #     rules:
  #     - alert: High Pod Memory
  #       expr: sum(container_memory_usage_bytes) > 1
  #       for: 1m
  #       labels:
  #         severity: slack
  #       annotations:
  #         summary: High Memory Usage
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    # rule_files:
    #   - /etc/prometheus/prometheus.rules
    # alerting:
    #   alertmanagers:
    #   - scheme: http
    #     static_configs:
    #     - targets:
    #       - "alertmanager.monitoring.svc:9093"
    scrape_configs:
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_endpoints_name]
          regex: 'node-exporter'
          action: keep
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      nodeSelector:
        "openebs.io/nodegroup": "storage-node"
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
              name: http
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 9090
            initialDelaySeconds: 10
            timeoutSeconds: 10
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
              readOnly: false
            - name: prometheus-data-volume
              mountPath: /data/
              readOnly: false
      volumes:
        - name: prometheus-data-volume
          persistentVolumeClaim:
            claimName: prometheus-data-claim
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
