---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: routeros-controller-secret
  namespace: routeros-controller
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: routeros-controller-secret
  dataFrom:
    - extract:
        key: /routeros-controller/routeros-controller-secret
---
