---
- name: Install k3s worker service
  tags: k3s
  block:
    - name: Copy K3s service file
      template:
        src: k3s.service.j2
        dest: /etc/systemd/system/k3s.service
        owner: root
        group: root
        mode: 0755

    # For consistent, reasonable DNS resolution
    - name: Write the custom nameserver file
      copy:
        content: |
          nameserver 8.8.8.8
          nameserver 1.1.1.1
        dest: /etc/k3s-resolv.conf

    - name: Enable and check K3s service
      systemd:
        name: k3s
        daemon_reload: true
        state: restarted
        enabled: true

    - name: Install disk & filesystem tools
      apt:
        pkg:
          - open-iscsi

    - name: Enable iscsi service
      systemd:
        name: iscsid
        daemon_reload: true
        state: restarted
        enabled: true
