---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # create namespace first
  - namespace.yaml
  - adguardhome-flux.yaml
  - adguardhome.yaml
configMapGenerator:
  - name: adguardhome-config
    namespace: adguardhome
    files:
      - adguardhome-config.yaml=adguardhome-config.yaml
---
