---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: kubernetes-replicator-image-repository
  namespace: kubernetes-replicator
spec:
  image: quay.io/mittwald/kubernetes-replicator
  interval: 30m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: kubernetes-replicator-image-policy
  namespace: kubernetes-replicator
spec:
  imageRepositoryRef:
    name: kubernetes-replicator-image-repository
  filterTags:
    pattern: '^v(?P<version>2\.[0-9]{1,2}\.[0-9]{1,2})$'
    extract: '$version'
  policy:
    semver:
      range: '>= 2.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: kubernetes-replicator-image-update-automation
  namespace: kubernetes-replicator
spec:
  interval: 30m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: flux@noreply.kja.us
        name: Flux
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: master
  update:
    path: ./kubernetes/infrastructure/controllers/kubernetes-replicator
    strategy: Setters
---
