---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubernetes-replicator
  namespace: kubernetes-replicator
spec:
  interval: 30m
  chart:
    spec:
      chart: kubernetes-replicator
      sourceRef:
        kind: HelmRepository
        name: mittwald
        namespace: flux-system
      interval: 30m
  values:
    image:
      tag: v2.9.1  # {"$imagepolicy": "kubernetes-replicator:kubernetes-replicator-image-policy:tag"}
    grantClusterAdmin: true
---
