---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - cilium.yaml
  # must come after helm release
  - cilium-configs.yaml
configMapGenerator:
  - name: cilium-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
