---

- hosts: kates_nodes
  gather_facts: true
  roles:
    - role: friendly-shell
      tags: friendly-shell
    - role: k3s-cluster/prereq
      become: true
    - role: k3s-cluster/download
      tags: k3s
      become: true

- hosts: kates_servers[0]
  become: true
  roles:
    - role: k3s-cluster/server
      tags: k3s
    - role: k3s-cluster/kubeconfig-local
      tags: kubeconfig

# Doing these one at a time because of etcd issues
# https://github.com/k3s-io/k3s/issues/2306
- hosts: kates_servers[1]
  become: true
  vars:
    extra_server_args: "--server https://{{ master_host }}:6443 --token {{ hostvars[groups['kates_servers'][0]]['token'] }}"
  roles:
    - role: k3s-cluster/server
      tags: k3s

- hosts: kates_servers[2]
  become: true
  vars:
    extra_server_args: "--server https://{{ master_host }}:6443 --token {{ hostvars[groups['kates_servers'][0]]['token'] }}"
  roles:
    - role: k3s-cluster/server
      tags: k3s

- hosts: kates_workers
  become: true
  roles:
    - role: k3s-cluster/worker
      tags: k3s

- hosts: kates_workers[0:1]
  become: true
  roles:
    - role: k3s-cluster/storage
      tags: storage
