- hosts: outland
  gather_facts: true
  roles:
    - role: common-apt
    - role: debian-base
    # - role: suricata
    - role: friendly-shell
    # use ufw rate limiting instead
    # - role: fail2ban
    # - role: dnsmasq
    #   vars:
    #     dns_root: "{{ ansible_default_ipv4.address }}"
    # - role: adguardhome
    #   vars:
    #     dns_root: "{{ ansible_default_ipv4.address }}"
    - role: k3s-cluster/prereq
      become: true
    - role: k3s-cluster/download
      become: true
    - role: k3s-cluster/server
      become: true
      vars:
        dns_root: "{{ ansible_default_ipv4.address }}"
        master_host: "{{ ansible_host }}"
    - role: k3s-cluster/kubeconfig-local
      vars:
        master_host: "{{ ansible_host }}"
    # - role: wireguard
    #   vars:
    #     wireguard_port: "26668"
    #     default_interface: eno1
