- name: Install asdf
  tags: ["asdf", "friendly-shell"]
  block:
    - name: Clone asdf repo
      git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: "{{ user_home }}/.asdf"
        version: "v{{ asdf_version }}"
        depth: 1
    - name: Create asdf completions directory
      file:
        path: "{{ user_home }}/.config/fish/completions"
        state: directory
        mode: 0755
    - name: Link asdf completions
      file:
        src: "{{ user_home }}/.asdf/completions/asdf.fish"
        dest: "{{ user_home }}/.config/fish/completions/asdf.fish"
        state: link
