---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mysql-backup-cronjob.yaml
  - mysql-backup-externalsecret.yaml
configMapGenerator:
  - name: mysql-backup-scripts
    namespace: azerothcore
    files:
      - make_backup.sh=make_backup.sh
---
