dependencies:
  - role: friendly-shell/asdf
  - role: friendly-shell/chezmoi
  - role: friendly-shell/fish
  - role: friendly-shell/motd
  - role: friendly-shell/starship
  - role: friendly-shell/k9s
