---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-secret
  namespace: gitea
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gitea-secret
  dataFrom:
    - extract:
        key: /gitea/gitea-secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-runner-secret-alpha
  namespace: gitea
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gitea-runner-secret-alpha
  dataFrom:
    - extract:
        key: /gitea/act-runner-secret-alpha
---
