---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: godaddy-api-key
  namespace: cert-manager
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: godaddy-api-key
  dataFrom:
    - extract:
        key: /cert-manager/godaddy-api-key
---
