---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 30m
  chart:
    spec:
      chart: kyverno
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
      interval: 30m
  values:
    crds:
      install: true

    grafana:
      enabled: true
      annotations:
        grafana_folder: Kyverno

    backgroundController:
      serviceMonitor:
        enabled: true

      rbac:
        clusterRole:
          extraResources:
            - apiGroups:
                - ""
              resources:
                - pods
              verbs:
                - create
                - update
                - patch
                - delete
                - get
                - list
            - apiGroups:
                - ""
              resources:
                - namespaces
              verbs:
                - get
                - list
                - watch

    cleanupController:
      serviceMonitor:
        enabled: true

    reportsController:
      serviceMonitor:
        enabled: true

    admissionController:
      replicas: 1

      rbac:
        clusterRole:
          extraResources:
            - apiGroups:
                - ""
              resources:
                - pods
              verbs:
                - create
                - update
                - delete

      serviceMonitor:
        enabled: true
