- name: Download Firefox package
  become: true
  unarchive:
    src: "https://download-installer.cdn.mozilla.net/pub/firefox/releases/{{ firefox_version }}/linux-x86_64/en-US/firefox-105.0.1.tar.bz2"
    dest: /opt
    remote_src: true
- name: Create desktop entry directory
  file:
    path: "{{ user_home }}/.local/share/applications"
    state: directory
- name: Create desktop entry
  copy:
    src: firefox-stable.desktop
    dest: "{{ user_home }}/.local/share/applications/firefox-stable.desktop"
