- name: Download Firefox package
  get_url:
    url: https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=en-US
    dest: /tmp/firefox.tar.bz2
- name: Unbzip Firefox package
  become: true
  unarchive:
    src: /tmp/firefox.tar.bz2
    dest: /opt
    remote_src: true
- name: Remove download artifact
  file:
    path: /tmp/firefox.tar.bz2
    state: absent
- name: Create desktop entry directory
  file:
    path: "{{ user_home }}/.local/share/applications"
    state: directory
- name: Create desktop entry
  copy:
    src: firefox-stable.desktop
    dest: "{{ user_home }}/.local/share/applications/firefox-stable.desktop"
