- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto
- name: Download & install nerd font for powerline-ish shell
  when: "'fontconfig' in ansible_facts.packages"
  block:
    - name: Create the user fonts directory
      file:
        path: "{{ user_home }}/.local/share/fonts"
        state: directory
    - name: Download & unarchive nerd fonts into user fonts directory
      unarchive:
        src: "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/{{ item }}"
        dest: "{{ user_home }}/.local/share/fonts"
        remote_src: true
      loop:
        - Cousine.zip
        - NerdFontsSymbolsOnly.zip
        - SourceCodePro.zip
        - InconsolataLGC.zip
        - FiraCode.zip
    - name: Download DM Mono font into user fonts directory
      get_url:
        url: "https://raw.githubusercontent.com/googlefonts/dm-mono/main/exports/{{ item }}"
        dest: "{{ user_home }}/.local/share/fonts"
      loop:
        - DMMono-Italic.ttf
        - DMMono-Light.ttf
        - DMMono-LightItalic.ttf
        - DMMono-Medium.ttf
        - DMMono-MediumItalic.ttf
        - DMMono-Regular.ttf
    - name: Refresh the font cache
      command: fc-cache
