---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: transmission-secret
  namespace: mediapipe
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: transmission-secret
  dataFrom:
    - extract:
        key: /mediapipe/transmission-secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wireguard-secret
  namespace: mediapipe
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: wireguard-secret
  dataFrom:
    - extract:
        key: /mediapipe/wireguard-secret
---
