---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-common-ingress-annotations
  annotations:
    policies.kyverno.io/title: Add Common Ingress Annotations
    policies.kyverno.io/subject: Ingress,Annotation
    policies.kyverno.io/description: >-
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
    - name: add-ingress-annotations
      match:
        any:
          - resources:
              kinds:
                - Ingress
      mutate:
        targets:
          - apiVersion: networking.k8s.io/v1
            kind: Ingress
            namespace: "{{ request.object.metadata.namespace }}"
        patchStrategicMerge:
          metadata:
            annotations:
              +(nginx.ingress.kubernetes.io/limit-rpm): "100"
              +(nginx.ingress.kubernetes.io/limit-whitelist): "192.168.1.0/24,192.168.2.0/24,10.42.0.0/16,10.43.0.0/16"
              +(nginx.ingress.kubernetes.io/whitelist-source-range): "192.168.1.0/24,192.168.2.0/24,10.42.0.0/16,10.43.0.0/16"
---

