---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - add-emptydir-sizelimit.yaml
  # - cluster-network-policy.yaml
  # - common-ingress-annotations.yaml
  - sync-outland-wildcard-tls-cert.yaml
---
