---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: lidarr-image-repository
  namespace: mediapipe
spec:
  image: docker.io/linuxserver/lidarr
  interval: 30m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: lidarr-image-policy
  namespace: mediapipe
spec:
  imageRepositoryRef:
    name: lidarr-image-repository
  filterTags:
    pattern: '^develop-(?P<version>1\.[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,5})-ls(?P<lsrev>[0-9]+)$'
    extract: '$version$lsrev'
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: lidarr-image-update-automation
  namespace: mediapipe
spec:
  interval: 30m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: flux@noreply.kja.us
        name: Flux
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: master
  update:
    path: ./kubernetes/apps/mediapipe/lidarr
    strategy: Setters
---
