apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidarr
  namespace: mediapipe
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "1.5.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  values:
    controller:
      type: statefulset
    image:
      repository: lscr.io/linuxserver/lidarr
      pullPolicy: IfNotPresent
      # tag: nightly-1.3.3.3415-ls89
      tag: develop-1.3.5.3530-ls104 # {"$imagepolicy": "mediapipe:lidarr-image-policy:tag"}
    env:
      DATA_FOLDER: "config"
      PUID: "1000"
      PGID: "1000"
      TZ: America/New_York
    service:
      main:
        ports:
          http:
            port: 8686
    ingress:
      main:
        annotations:
          nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
          nginx.ingress.kubernetes.io/server-snippets: |
            location / {
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "upgrade";
        enabled: true
        hosts:
          - host: &host lidarr.flight.kja.us
            paths:
              - path: /
                pathType: Prefix
        ingressClassName: nginx
        tls:
          - hosts:
              - *host
    # podSecurityContext:
    #   runAsUser: 1000
    #   runAsGroup: 1000
    #   fsGroup: 1000
    #   fsGroupChangePolicy: "OnRootMismatch"
    #   supplementalGroups:
    #     - 65539
    resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 799M
    # requests:
    # cpu: 5m
    # memory: 799M
    persistence:
      config:
        enabled: true
        hostPath: /data/lidarr
        mountPath: /config
        type: hostPath
      music:
        enabled: true
        hostPath: /data/media/music
        mountPath: /music
        type: hostPath
      downloads:
        enabled: true
        hostPath: /data/media/downloads
        mountPath: /downloads
        type: hostPath
      rescycle-bin:
        enabled: true
        hostPath: /data/media/recycle-bin
        mountPath: /recycle-bin
        type: hostPath
