- name: Install Sublime Text
  become: true
  block:
    - name: Add Sublime Text apt key
      shell: wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | gpg --dearmor | tee /etc/apt/keyrings/sublimehq-archive.gpg
    - name: Add Sublime Text repository
      apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/sublimehq-archive.gpg] https://download.sublimetext.com/ apt/stable/
        state: present
        filename: sublime-text.list
    - name: Install Sublime Text
      apt:
        update_cache: true
        pkg: sublime-text
